# Generated by Django 5.0.6 on 2024-06-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_txt', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.question')),
            ],
        ),
    ]
